In [1]:
from data import Poetry
from model import lstm_char
from tqdm import tqdm

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import fitlog
import os

In [2]:
from data import Poetry
from model import lstm_char
from tqdm import tqdm

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import fitlog
import os

device = torch.device('cuda:1') if torch.cuda.is_available() else torch.device('cpu')

model_save_path = "./models"
result_save_path = "./result"

data = Poetry()

vocab_size = len(data.word_to_id)

model = lstm_char(vocab_size).to(device)

optimizer = optim.Adam(model.parameters(), lr=0.001)

loss_function = nn.CrossEntropyLoss()

In [47]:
model.load_state_dict(torch.load("./models/epoch_100_model.pkl"))

<All keys matched successfully>

In [5]:
data.word_to_id["雪"]
device


device(type='cuda', index=1)

In [6]:
out,_ = model(torch.tensor([[5451]]).to(device),device)


In [7]:
out.shape

torch.Size([1, 5938])

In [12]:
b = torch.argmax(out)

In [16]:
int(b)

2019

In [49]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    # 将除了top_n个预测值的位置都置为0
    p[np.argsort(p)[:-top_n]] = 0
    # 归一化概率
    p = p / np.sum(p)
    # 随机选取一个字符
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [53]:
pick_top_n(out.cpu().detach().numpy(), vocab_size)

4528

In [56]:
c = "雪"

result = [i for i in c]
id = 0

while True:
    if id>50:
        break
    out = [data.word_to_id[i] for i in c]
    print(out)
    out,_ = model(torch.tensor([out]).to(device), device)
    print(out[-1])
    b = pick_top_n(out[-1].cpu().detach().numpy(), vocab_size)
    print(b)
    c = data.id_to_word[int(b)]
    result.append(c)
    print(result)
    print("".join(result))
    id += 1
    

[5451]
tensor([ -0.5763, -36.9647,  26.6522,  ..., -21.1932, -79.5755, -58.6665],
       device='cuda:1', grad_fn=<SelectBackward>)
997
['雪', '婉']
雪婉
[997]
tensor([-9.6116, 35.6966,  2.6065,  ..., 50.1033, 42.1176, 43.2135],
       device='cuda:1', grad_fn=<SelectBackward>)
3166
['雪', '婉', '皂']
雪婉皂
[3166]
tensor([ 10.2078, -11.6741,  14.7772,  ..., -48.1027,  26.5218,  -1.9215],
       device='cuda:1', grad_fn=<SelectBackward>)
2423
['雪', '婉', '皂', '污']
雪婉皂污
[2423]
tensor([ -8.4021, -34.3792,   0.7733,  ...,  -0.2996,  11.2703,   5.7000],
       device='cuda:1', grad_fn=<SelectBackward>)
77
['雪', '婉', '皂', '污', '亏']
雪婉皂污亏
[77]
tensor([-10.0685, -47.0146,  -0.7667,  ..., -30.5467,  -7.9632,   4.9828],
       device='cuda:1', grad_fn=<SelectBackward>)
4314
['雪', '婉', '皂', '污', '亏', '蔷']
雪婉皂污亏蔷
[4314]
tensor([  8.9674,  -3.3118,  10.2191,  ..., -10.0306,   8.6038, -16.7455],
       device='cuda:1', grad_fn=<SelectBackward>)
2685
['雪', '婉', '皂', '污', '亏', '蔷', '滟']
雪婉皂污亏蔷滟
[2685]
tensor([-

tensor([-18.9504, -33.2352,  -5.5837,  ...,  38.7768,   4.9525, -23.8090],
       device='cuda:1', grad_fn=<SelectBackward>)
2336
['雪', '婉', '皂', '污', '亏', '蔷', '滟', '湘', '橹', '儿', '女', '宫', '瞰', '不', '禁', '瞰', '不', '磊', '柏', '板', '，', '君', '踪', '该', '沈', '黼', '愤', '激', '，', '秋', '，', '人', '唱', '遣', '旅', '消', '戢', '徒', '涌', '欻']
雪婉皂污亏蔷滟湘橹儿女宫瞰不禁瞰不磊柏板，君踪该沈黼愤激，秋，人唱遣旅消戢徒涌欻
[2336]
tensor([  3.3765, -27.0040,  10.5318,  ...,  -6.2783, -25.0650, -18.2985],
       device='cuda:1', grad_fn=<SelectBackward>)
2083
['雪', '婉', '皂', '污', '亏', '蔷', '滟', '湘', '橹', '儿', '女', '宫', '瞰', '不', '禁', '瞰', '不', '磊', '柏', '板', '，', '君', '踪', '该', '沈', '黼', '愤', '激', '，', '秋', '，', '人', '唱', '遣', '旅', '消', '戢', '徒', '涌', '欻', '条']
雪婉皂污亏蔷滟湘橹儿女宫瞰不禁瞰不磊柏板，君踪该沈黼愤激，秋，人唱遣旅消戢徒涌欻条
[2083]
tensor([ -2.4915, -34.3290, -10.1758,  ..., -11.9709, -47.3204, -55.2727],
       device='cuda:1', grad_fn=<SelectBackward>)
5083
['雪', '婉', '皂', '污', '亏', '蔷', '滟', '湘', '橹', '儿', '女', '宫', '瞰', '不', '禁', '瞰', '不', '磊', '柏', '板', '，', 

In [17]:
data.id_to_word[int(b)]

'曈'

In [ ]:
c = "日照香炉生紫烟"